project:
  type: website
  output-dir: docs

website:
  title: "Kenya Census 2026"
  navbar:
    left:
      - text: "Surveys"
        href: surveys.qmd
      - text: "Background"
        href: background.qmd
      - text: "Education"
        href: educ.qmd
      - text: "Sustainability"
        href: sustainability.qmd
      - text: "Health"
        href: health.qmd
      - text: "Water"
        href: water.qmd
      - text: "Economic Development"
        href: econ.qmd
      - text: "Hope"
        href: hope.qmd       

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
